title: "DisCouRSE: Developing a Community of Leaders"
logo: "assets/images/DisCouRSE-Logo-Light.svg"
email: 
description: >- # this means to ignore newlines until "baseurl:"
   DisCouRSE is a UKRI-funded Network+ project that will encourage and support the development of leaders
   across all digital Research Technical Professional (dRTP) roles, resulting in an empowered and connected
   community equipped to shape the future of digital research. 
github:
  is_project_page: false
search: true

# Navigation
navigation:
  header: main

sidebar:
  disable: true
  
collections:
  team:
    output: true
    permalink: /team/:name/
  events:
    output: true
    permalink: /:collection/:path/

feed:
  posts_limit: 20
  collections:
    - events
atom_feed:
  path: "/feed/events.xml"

# This is needed or pages for future events are not generated!
future: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes

include:
  - _includes/head_custom.html

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Plugins (previously gems:):
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
#  name: "DisCouRSE"
#  avatar: "/assets/images/bio-photo.jpg"
#  bio: "DisCouRSE: Developing a Community of Leaders"
#  links:
#    - label: "Website"
#      icon: "fas fa-fw fa-link"
#      url: "https://"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"

copyright: "DisCouRSE, which has received funding through the UKRI Digital Research Infrastructure Programme"

footer:
  since: "2025"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/company/discourse-network"
#    - label: "Twitter"
#      icon: "fab fa-fw fa-twitter-square"
#      url: "https://twitter.com/"
#    - label: "GitHub"
#      icon: "fab fa-fw fa-github"
#      url: "https://github.com/"
#    - label: "Instagram"
#      icon: "fab fa-fw fa-instagram"
#      url: "https://instagram.com/"

# Sidebar enabled and custom content (text widget)
sidebar: false

## Sidebar content for the widgets
#sidebar_widgets:
#  - text:
#      title: "Welcome to DisCouRSE"
#      content: |
#        This is the sidebar where you can include some introductory text.
#        You can also provide more details about the site, upcoming events, 
#        or anything else you'd like visitors to see while navigating the site.
#        
#        Feel free to customize the content to match your theme and goals.

# Page defaults
defaults:
  # Pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page  # Set layout for pages
      author_profile: false

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# In _config.yml
minimal_mistakes_skin: default
sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      css: "/assets/css/main.css"
